# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true

target 'prowash_app_mobile' do
  use_frameworks! :linkage => :static
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    fmt_header = File.join(
      installer.sandbox.root.to_s,
      'fmt/include/fmt/base.h'
    )

    if File.file?(fmt_header)
      File.chmod(File.stat(fmt_header).mode | 0o200, fmt_header)
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Xcode 27: pods must target iOS >= 15
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

        if deployment_target.nil? || deployment_target.to_f < 15.1
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
      end
    end

    # Xcode 26.4+/27 workaround for old fmt bundled with React Native
    fmt_base = File.join(
      installer.sandbox.pod_dir('fmt'),
      'include',
      'fmt',
      'base.h'
    )

    if File.exist?(fmt_base)
      content = File.read(fmt_base)

      patched = content.gsub(
        /#  define FMT_USE_CONSTEVAL 1/,
        '#  define FMT_USE_CONSTEVAL 0'
      )

      File.write(fmt_base, patched)
    end
  end
end
